/*************************************************************
Author: Hao Dong
Email:  hao.dong.nanjing@outlook.com
*************************************************************/

#include "pid.h"

/*************************************************************  

    kp and ki are the parameter generated by s transfer function
    Transfer function : 
                      ki
        G(s) = kp + ------
                      s
    Actually, the corresponding transfer function in z domain:
                        ki * z
        G(z) = kp + ---------------
                        z - 1 
*************************************************************/
void pid_init(pidStruct * s, float kp, float ki, float ts) {
    s->kp = kp ;
    s->ts = ts ;
    s->ki = ki * ts ;
    s->sum_ki = 0.0f ;
    s->output = 0.0f ;
    s->reference = 0.0f ;
}

/**
 * PI controller is really simple, you can implement anti-saturation or other features by yourself
**/
float pid_calc(pidStruct * s, float feedback) {
    float error = s->reference - feedback ;
    s->sum_ki += s->ki * error ;
    s->output = s->sum_ki + s->kp * error ;
    return s->output ;
}
