/*************************************************************
Author: Hao Dong
Date: 2018.06.23
Email:  hao.dong.nanjing@gmail.com
*************************************************************/

#include "pid.h"

// kp and ki are the parameter generated by s transfer function
void Init_pidStruct(pidStruct * s, float kp, float ki) {
    s->kp = kp ;
    s->ki = ki * T_CONTROL ;
    s->sum_ki = 0 ;
    s->output = 0 ;
    s->reference = 0 ;
}

float Calc_pidStruct(pidStruct * s, float feedback) {
    float error = s->reference - feedback ;
    s->sum_ki += s->ki * error ;

    if(s->sum_ki > 0.85f){
        s->sum_ki = 0.85f ;
    }
    else if( s->sum_ki < -0.85f){
        s->sum_ki = -0.85f;
    }
    s->output = s->sum_ki + s->kp * error ;
    return s->output ;
}
