/*************************************************************
Author: Hao Dong
Date: 2018.06.23
Email:  hao.dong.nanjing@outlook.com
*************************************************************/

#include "pid.h"

/*************************************************************  

    kp and ki are the parameter generated by s transfer function
    Transfer function : 
                      ki
        G(s) = kp + ------
                      s
    Actually, the corresponding transfer function in z domain:
                        ki * z
        G(z) = kp + ---------------
                        z - 1 
*************************************************************/
void Init_pidStruct(pidStruct * s, double kp, double ki, double ts) {
    s->kp = kp ;
    s->ts = ts ;
    s->ki = ki * ts ;
    s->sum_ki = 0 ;
    s->output = 0 ;
    s->reference = 0 ;
}

double Calc_pidStruct(pidStruct * s, double feedback) {
    double error = s->reference - feedback ;
    s->sum_ki += s->ki * error ;
    s->output = s->sum_ki + s->kp * error ;
    return s->output ;
}
